spring:
  profiles:
    active: dev  # Change to 'dev' when running locally, 'prod' for production

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:remindlydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  server:
    port: 8080
  mail:
    host: smtp.gmail.com
    port: 587
    username: verma.aditya1999@gmail.com
    password: ##
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account-sid:  ##
  auth-token: ##
  from-number: whatsapp:+##

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/remindly
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_prod_user
    password: your_secure_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  server:
    port: 8080
